version: "3"
services:
  # API Server
  server:
    container_name: sorasvl-server
    build:
      context: ./server
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - sorasvl

  # Client
  client:
    container_name: sorasvl-client
    build:
      context: ./sorasvl-client
    ports:
      - "8080:3000"
    networks:
      - sorasvl

  # Nginx
  nginx:
    container_name: sorasvl-router
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - sorasvl
  
  # MongoDB
  mongo:
    container_name: sorasvl-mongo
    build:
      context: ./mongo
    ports:
      - "27017:27017"
    networks:
      - sorasvl

networks:
  sorasvl:
    driver: bridge
